version: '3.4'

services:
    postgres:
        image: postgres:12-alpine
        restart: unless-stopped
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./data/postgresql/var/lib/postgresql/data:/var/lib/postgresql/data:delegated
        hostname: postgres
        domainname: test
        container_name: dde_postgres
