version: '3.4'
services:
    demo:
        build:
            context: "."
            target: dev
        environment:
            - VIRTUAL_HOST=dde-demo.test
            - SSH_AUTH_SOCK=/tmp/ssh-agent/socket
        volumes:
            - sync:/var/www:nocopy
            - ssh-agent_socket-dir:/tmp/ssh-agent:ro
        hostname: dde-demo
        domainname: test
        container_name: dde_demo

networks:
    default:
        external:
            name: "dde"

volumes:
    ssh-agent_socket-dir:
        external:
            name: dde_ssh-agent_socket-dir
    sync:
        external:
            name: dde_demo_sync
